# Generated by Django 5.1 on 2024-09-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassType',
            new_name='ClassTypes',
        ),
    ]
