# Generated by Django 5.1 on 2024-09-28 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_rename_classtype_classtypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('image', models.ImageField(upload_to='img')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('class_type', models.ManyToManyField(to='railway.classtypes')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_trains', to='railway.station')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_trains', to='railway.station')),
            ],
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
