# Generated by Django 5.1 on 2024-11-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_train_data_delete_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
