# Generated by Django 5.1 on 2024-11-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0005_train_data_departure_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train_data',
            name='departure_date',
        ),
    ]
