# Generated by Django 5.1 on 2024-11-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0006_remove_train_data_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_data',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
