# Generated by Django 5.1 on 2024-11-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0008_booking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
