# Generated by Django 5.1 on 2024-11-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0009_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=3)),
                ('seat_preference', models.CharField(choices=[('Window', 'Window'), ('Aisle', 'Aisle'), ('Middle', 'Middle')], max_length=10)),
                ('passenger_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=15)),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
