# Generated by Django 5.1 on 2024-11-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0010_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train_data',
            name='image',
        ),
    ]
