# Generated by Django 5.1 on 2024-11-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0011_remove_train_data_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
